### ISSUE TITLE
Error: ring.stations: function toString() { [native code] }

### ISSUE THREAD

**Issue by qnguye** [homespun/ring-alarm#8]
I've been using this for awhile. Suddenly, it stopped working yesterday and this is the error i got. Help me how to fix. Thanks

ring.stations: function toString() { [native code] }

**Comment by joeyberkovitz** [comment]
I had a similar issue a couple days ago, but I'm using my fork (https://github.com/joeyberkovitz/ring-alarm)
The solution to my problem was to delete the cache file, which generates a new hardware ID and auth token, but that functionality doesn't exist in this version of the code.

Try running your script as `DEBUG=* node script.js` where script.js is whatever script you were running and send some of the debug information (with relevant authentication tokens and details filtered out) so that it would be possible to figure out exactly what error you're getting.

**Comment by qnguye** [comment]
I ran debug mode and things back to normal. I guess debug mode also cleared the cache. It's working for me now. Thank you!
